### ISSUE TITLE
Why is not JS support?

### ISSUE THREAD

**Issue by gybfefe** [philsinatra/htmlNestedCommentsVSCode#4]
It's basic, and it steals the shortcut from the working one.... could not be hard as it's just toggle //, however if you wanna stay systematic then change on js files // to ~~ too, would be nice.... If you support vue, I really don't understand how on earth leave out JS extension..... :)
Appreciate your work.
Thanx,
Ben

**Comment by philsinatra** [comment]
Support for `.js` files is not included because the editor can handle nested comments fine in `.js` by default. The extension is specifically for `.html` syntax comments because for whatever reason the native commenting of the editor can't handle nested comments.

I did however just publish a patch that changes the default keybinding so that the package does not hijack the default comment binding on Windows.

Support for `.vue` is included because that syntax includes HTML formatting for comments.

**Comment by Armaldio** [comment]
Hello

Sorry to reopen this but the default shortcut doesn't work for me in JS files


![ezgif com-gif-maker](https://user-images.githubusercontent.com/3089715/99684275-90989a80-2a81-11eb-9b8e-4d7866b4bb08.gif)

**Comment by philsinatra** [comment]
JavaScript & Typescript files have native support for nested comments. This extension does not infringe on the default support included with VSCode for .js or .ts files. You should be able to use the standard comment shortcut in those cases.

**Comment by Armaldio** [comment]
As shown in the video I am indeed using the default shortcut

**Comment by philsinatra** [comment]
The extension is not intended to work in JavaScript/Typescript files. You should use the standard commenting shortcut in those file types, not this extension. If your editor is setup to use the `/* */` format instead of `//` by default, that would be an issue with your config, not something related to this extension.
